<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Learning.Application\Learning.Application.csproj" />
    <ProjectReference Include="..\..\enrollment\Enrollments.Contracts\Enrollments.Contracts.csproj" />
    <ProjectReference Include="..\Learning.Contracts\Learning.Contracts.csproj" />
    <ProjectReference Include="..\..\..\building-blocks\BuildingBlocks.Messaging\BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Learning.Integration.Tests" />
    <InternalsVisibleTo Include="Learning.Component.Tests" />
  </ItemGroup>

</Project>
